### ISSUE TITLE
Show Log not possible for selected Job if self-signed or invalid SSL certificate is used

### ISSUE THREAD

**Issue by chen1234hao** [MCMicS/jenkins-control-plugin#217] opened 2020-06-02 03:09 UTC
- [x] My RSS icon is dark
- [x] why i can not refresh last completed builds
- [ ] can not show log

**Comment by MCMicS** [comment] 2020-06-02 05:38
Refresh currently reloads the view and close all expanded tree.

 An enhancement is to reefresh the current state so loaded builds are reloaded too.
But this is not implemented yet

Which logs cannot be shown? Do you got an error? In genral you can show your last log from context menu.

> My RSS icon is dark

The Icon exist in two variant (theme controlled) but both are not orange because the idea color guide says to use plain colors and use colors for build states, errors and so on.
Do you expect an orange icon?

**Comment by chen1234hao** [comment] 2020-06-02 06:17
> Refresh currently reloads the view and close all expanded tree.
> 
> An enhancement is to reefresh the current state so loaded builds are reloaded too.
> But this is not implemented yet
> 
> Which logs cannot be shown? Do you got an error? In genral you can show your last log from context menu. --  when i click show log in context menu, i got an error "could not find job data for ***********"
> 
> > My RSS icon is dark
> 
> The Icon exist in two variant (theme controlled) but both are not orange because the idea color guide says to use simple icons and forms and use colors for build states, errors and so on.
> Do you expect an orange icon?

**Comment by MCMicS** [comment] 2020-06-02 06:32
> could not find job data for ***********

If you open the URL (shown in message) in  browser will it works?

**Comment by chen1234hao** [comment] 2020-06-02 06:40
> > could not find job data for ***********

> If you open the URL (shown in message) in browser will it works?   yes, the URL can open in my browse. also i can successfully click go to the job page or go to the last build page in context menu.
it will jump to the browse page.
it just can not show log in my idea.

**Comment by MCMicS** [comment] 2020-06-02 06:43
hmm. I have to look more. It could happen if the job is not found (by full name) on server

It is possible to test against the server?

**Comment by chen1234hao** [comment] 2020-06-02 07:00
> hmm. I have to look more. It could happen if the job is not found (by full name) on server
> 
> It is possible to test against the server?
the job can be build by click the build on jenkins in context menu, the server can find the job too.
Thans for your quick reply.

**Comment by MCMicS** [comment] 2020-06-02 07:04
The log action use a different external library than the run build action.

Is it possible to use your jenkins or could you send me the job name to verify that??
You can also private message me in Gitter chat

**Comment by chen1234hao** [comment] 2020-06-02 07:12
> The log action use a different external library than the run build action.
> 
> Is it possible to use your jenkins or could you send me the job name to verify that??  i think you have no permission to visit our Jenkins servers. the full job https://ged-vs.jenkins.bshg.com/job/TESTING_PROJECTS/job/PRF_CT_SBS_NF/job/PLAYGROUND/job/DEFAULT/

**Comment by MCMicS** [comment] 2020-06-02 07:14
I will have a detailed look later the day on this.
I try to reproduce it with the Job structure

**Comment by MCMicS** [comment] 2020-06-02 18:19
I've tested your structure and my log will open.
![grafik](https://user-images.githubusercontent.com/4604206/83554773-91f2fc80-a50d-11ea-88bd-120fef8e6078.png)

Could you send a screen of your job structure

**Comment by chen1234hao** [comment] 2020-06-03 00:43
> Could you please enable more logging.
> Help > (Diagnostic Tools >) Debug Log Settings and add:
> 
> > com.offbytwo.jenkins.JenkinsServer
> 
> Then you should get in idea.log following line if error occurs:
> 
> > 2020-06-02 20:37:14,789 [  78474]  DEBUG - offbytwo.jenkins.JenkinsServer - getJob(folder=null, jobName=TESTING_PROJECTS/job/PRF_CT_SBS_NF/job/PLAYGROUND/job/DEFAULT) status=404

I got the log below:
2020-06-03 08:42:51,922 [62582207]  ERROR - intellij.openapi.progress.Task - PyCharm 2020.1.1  Build #PC-201.7223.92 
2020-06-03 08:42:51,924 [62582209]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-06-03 08:42:51,924 [62582209]  ERROR - intellij.openapi.progress.Task - OS: Windows 10 
2020-06-03 08:42:51,924 [62582209]  ERROR - intellij.openapi.progress.Task - Plugin to blame: Jenkins Control Plugin version: 0.13.3-2020.1 
2020-06-03 08:42:51,924 [62582209]  ERROR - intellij.openapi.progress.Task - Last Action: TailIntelliJLog 
2020-06-03 08:42:52,818 [62583103]  ERROR - intellij.openapi.progress.Task - Can't get progress 
java.lang.RuntimeException: Can't get progress
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:230)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: com.intellij.util.IncorrectOperationException: Sorry but parent: Project (name=TST_CIT_MD, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\chenhao2\PycharmProjects\TST_CIT_MD)  has already been disposed (see the cause for stacktrace) so the child: null 364346079: running=false; canceled=false; task=null will never be disposed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:227)
	... 4 more
Caused by: com.intellij.util.IncorrectOperationException: Sorry but parent: Project (name=TST_CIT_MD, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\chenhao2\PycharmProjects\TST_CIT_MD)  has already been disposed (see the cause for stacktrace) so the child: null 364346079: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:59)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:65)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:90)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:75)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:49)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:45)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:41)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$runProcessWithProgressAsynchronously$2(ProgressManagerImpl.java:107)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.util.concurrency.PlainEdtExecutor.execute(PlainEdtExecutor.java:15)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:106)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runAsynchronously(CoreProgressManager.java:351)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:338)
	at com.intellij.openapi.progress.Task.queue(Task.java:109)
	at org.codinjutsu.tools.jenkins.util.GuiUtil$TaskRunner.run(GuiUtil.java:69)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by chen1234hao** [comment] 2020-06-03 00:45
> Could you please enable more logging.
> Help > (Diagnostic Tools >) Debug Log Settings and add:
> 
> > com.offbytwo.jenkins.JenkinsServer
> 
> Then you should get in idea.log following line if error occurs:
> 
> > 2020-06-02 20:37:14,789 [  78474]  DEBUG - offbytwo.jenkins.JenkinsServer - getJob(folder=null, jobName=TESTING_PROJECTS/job/PRF_CT_SBS_NF/job/PLAYGROUND/job/DEFAULT) status=404



> I've tested your structure and my log will open.
> ![grafik](https://user-images.githubusercontent.com/4604206/83554773-91f2fc80-a50d-11ea-88bd-120fef8e6078.png)
> 
> Could you send a screen of your job structure

sorry i can't upload picture here

**Comment by MCMicS** [comment] 2020-06-03 06:06
your stacktrace is another issue (#186)

But I  cannot see the debug log

**Comment by MCMicS** [comment] 2020-06-03 06:08
Please set the debug level and restart the ide and reproduce the error

**Comment by chen1234hao** [comment] 2020-06-03 06:24
> Please set the debug level and restart the ide and reproduce the error
After set the debug level and restart the ide then reproduce the error, i can't see any error just below info.
2020-06-03 14:20:13,150 [ 121408]   INFO - lij.diagnostic.DebugLogManager - Set DEBUG for the following categories: com.offbytwo.jenkins.JenkinsServer

**Comment by MCMicS** [comment] 2020-06-03 06:27
hmm curious.
The error from stack occurs nmormally if only the project window is closed. But after a restart of the IDE it will gone. Then you should click 'Show log' from contect menu and the your first error should occur (with debug log)

**Comment by MCMicS** [comment] 2020-06-03 06:32
I've tested with PyCharm again but cannot get the error. may be an jenkins configuration issue
I can offer you an build with more log for testing

**Comment by chen1234hao** [comment] 2020-06-03 06:42
> I've tested with PyCharm again but cannot get the error. may be an jenkins configuration issue
> I can offer you an build with more log for testing

you are a great and patient developer.

**Comment by MCMicS** [comment] 2020-06-03 06:44
Do you use Password and Crumb for login or API token??
I saw in code that the logic not use the cxrumb and so it is possible that this call is not authentificated.

Can you please API token (http://<jenkins>/user/<user>/configure) and use the API token as Password?

This could help

**Comment by chen1234hao** [comment] 2020-06-03 06:47
> Do you use Password and Crumb for login or API token??
> I saw in code that the logic not use the cxrumb and so it is possible that this call is not authentificated.
> 
> Can you please API token (http:///user//configure) and use the API token as Password?
> 
> This could help

I use the API token as Password.

**Comment by MCMicS** [comment] 2020-06-03 07:13
[jenkins-control-plugin-0.13.3-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4721532/jenkins-control-plugin-0.13.3-2020.1-bug217.zip)

Could you try this plugin. If the error occurs it should appears as notification balloon

**Comment by chen1234hao** [comment] 2020-06-03 07:24
> [jenkins-control-plugin-0.13.3-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4721532/jenkins-control-plugin-0.13.3-2020.1-bug217.zip)
> 
> Could you try this plugin. If the error occurs it should appears as notification balloon

I use your attached plugin then got below ERROR
2020-06-03 15:20:38,509 [ 172307]  ERROR - s.jenkins.logic.RequestManager - PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target 
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by MCMicS** [comment] 2020-06-03 07:38
This look like an ssl issue for your jenkins.
Is this a real cert with valid chain?
Could you can use curl to verifiy this?

**Comment by chen1234hao** [comment] 2020-06-03 08:48
> This look like an ssl issue for your jenkins.
> Is this a real cert with valid chain?--how to check?
> Could you can use curl to verifiy this? -- sorry i don't know how to verify

**Comment by MCMicS** [comment] 2020-06-03 09:22
curl -v -u <user>:<token> <JenkinsUrl>/api/json

**Comment by MCMicS** [comment] 2020-06-03 17:28
If you got the output of `curl -v -u <user>:<token> <JenkinsUrl>/api/json` maybe I can see the problem

**Comment by chen1234hao** [comment] 2020-06-04 00:36
i got the below output
*   Trying 10.49.94.237...
* TCP_NODELAY set
* Connected to ged-vs.jenkins.bshg.com (10.49.94.237) port 443 (#0)
* schannel: SSL/TLS connection with ged-vs.jenkins.bshg.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 188 bytes...
* schannel: sent initial handshake data: sent 188 bytes
* schannel: SSL/TLS connection with ged-vs.jenkins.bshg.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with ged-vs.jenkins.bshg.com port 443 (step 2/3)
* schannel: encrypted data got 2819
* schannel: encrypted data buffer: offset 2819 length 4096
* schannel: sending next handshake data: sending 182 bytes...
* schannel: SSL/TLS connection with ged-vs.jenkins.bshg.com port 443 (step 2/3)
* schannel: encrypted data got 107
* schannel: encrypted data buffer: offset 107 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with ged-vs.jenkins.bshg.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
* Server auth using Basic with user 'chenhao2'
> GET /api/json HTTP/1.1
> Host: ged-vs.jenkins.bshg.com
> Authorization: Basic Y2hlbmhhbzI6MTFkN2QyNzVjOTAyZWE1ZjBkNzNiNWRlNGJiZWVlMDc3NA==
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 2661
* schannel: encrypted data buffer: offset 2661 length 103424
* schannel: decrypted data length: 2587
* schannel: decrypted data added: 2587
* schannel: decrypted data cached: offset 2587 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 2587 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 2587
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Date: Thu, 04 Jun 2020 00:33:44 GMT
< X-Content-Type-Options: nosniff
< X-Jenkins: 2.213
< X-Jenkins-Session: e48bbf78
< Content-Type: application/json;charset=utf-8
< Content-Length: 2350
< Server: Jetty(9.4.22.v20191022)
<
{"_class":"hudson.model.Hudson","assignedLabels":[{"name":"master"}],"mode":"NORMAL","nodeDescription":"the master Jenkins node","nodeName":"","numExecutors":3,"description":null,"jobs":[{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"ARTIFACT_HARVES
TER","url":"https://ged-vs.jenkins.bshg.com/job/ARTIFACT_HARVESTER/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"CBD_TOOLBOX","url":"https://ged-vs.jenkins.bshg.com/job/CBD_TOOLBOX/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name"
:"CHANGELOG_PARSER","url":"https://ged-vs.jenkins.bshg.com/job/CHANGELOG_PARSER/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"CTSWPL","url":"https://ged-vs.jenkins.bshg.com/job/CTSWPL/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","na
me":"GED_SEEC","url":"https://ged-vs.jenkins.bshg.com/job/GED_SEEC/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"GUARDIAN","url":"https://ged-vs.jenkins.bshg.com/job/GUARDIAN/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"HEAD
QUARTER","url":"https://ged-vs.jenkins.bshg.com/job/HEADQUARTER/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"MASON_TESTING_FRAMEWORK","url":"https://ged-vs.jenkins.bshg.com/job/MASON_TESTING_FRAMEWORK/"},{"_class":"com.cloudbees.hudson.plugins.
folder.Folder","name":"REQ_VAL","url":"https://ged-vs.jenkins.bshg.com/job/REQ_VAL/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"TEST_ABSTRACTION_LAYER","url":"https://ged-vs.jenkins.bshg.com/job/TEST_ABSTRACTION_LAYER/"},{"_class":"com.cloudbee
s.hudson.plugins.folder.Folder","name":"TestBusServer","url":"https://ged-vs.jenkins.bshg.com/job/TestBusServer/"},{"_class":"com.cloudbees.hudson.plugins.folder.Folder","name":"TESTING_GURU","url":"https://ged-vs.jenkins.bshg.com/job/TESTING_GURU/"},{"_class":"com
.cloudbees.hudson.plugins.folder.Folder","name":"TESTING_PROJECTS","url":"https://ged-vs.jenkins.bshg.com/job/TESTING_PROJECTS/"}],"overallLoad":{},"primaryView":{"_class":"hudson.model.AllView","name":"all","url":"https://ged-vs.jenkins.bshg.com/"},"quietingDown":
false,"slaveAgentPort":50000,"unlabeledLoad":{"_class":"jenkins.model.UnlabeledLoadStatistics"},"useCrumbs":true,"useSecurity":true,"views":[{"_class":"hudson.model.AllView","name":"all","url":"https://ged-vs.jenkins.bshg.com/"}]}* Connection #0 to host ged-vs.jenk
ins.bshg.com left intact

**Comment by MCMicS** [comment] 2020-06-04 04:58
Hmm. Looks fine on first look.

Its strange. The only I can see is that curl is need a second handshake.

> schannel: failed to receive handshake, need more data

I will try to setup this behaviour and reproduce it

**Comment by MCMicS** [comment] 2020-06-07 18:15
not found any way to reproduce it. Will setup a SSL jenkins and try again

**Comment by MCMicS** [comment] 2020-06-08 16:47
If I test against my Openshift setup I cannor connect with PyCharm.

But other tools seem to work, 
Have u the possibility to test with other IDE (Intellij or WebStorm) to verfify

**Comment by diman82** [comment] 2020-06-10 09:11
> `curl -v -u <user>:<token> <JenkinsUrl>/api/json`

I've got the same problem, and indeed it was an issue with certificate.
So after exporting certificate from browser, converting ir to pem format,I managed to successfully run it in curl command (and get json output).

How do I add this certificate to plugin?

**Comment by MCMicS** [comment] 2020-06-10 09:45
Currently not possible. You can import them to the executing jvm (JBR from IDE i think) or try use java environment variables

I can look tomorrow for a workaround

**Comment by diman82** [comment] 2020-06-10 10:03
> Currently not possible. You can import them to the executing jvm (JBR from IDE i think) or try use java environment variables
> 
> I can look tomorrow for a workaround

It would be great, if you could provide aome examples.
Java certificate import only accepts p12 & csr formats, ans I can export only CER format (from my browser)..

**Comment by MCMicS** [comment] 2020-06-11 06:09
@diman82 It is possible to test against your server?

Normally the IDE should bring a dialog that the certificate is untrusted and let u choose to add an exception.

**Comment by diman82** [comment] 2020-06-11 10:39
> @diman82 It is possible to test against your server?
> 
> Normally the IDE should bring a dialog that the certificate is untrusted and let u choose to add an exception.

Yes, its possible.
P.S. I've manually added the required certificate to IDE, but the plugin seems to ignore it..

**Comment by MCMicS** [comment] 2020-06-11 11:00
Can you send me your jenkins url to test against.
You can use gitter with private chat if it should not be public here in issue

**Comment by diman82** [comment] 2020-06-11 11:04
> Can you send me your jenkins url to test against.
> You can use gitter with private chat if it should not be public here in issue

Sorry, I've probably misunderstood you - my Jenkins instance is private (corporate), so external access is not possible.

**Comment by MCMicS** [comment] 2020-06-11 11:43
Ok no problem
Try to setup this the days

**Comment by MCMicS** [comment] 2020-06-14 18:43
Hi @chen1234hao , @diman82 , would you like to test following build please.
I changed the second http client to use the IDE settings (see 
![grafik](https://user-images.githubusercontent.com/4604206/84601266-2d299180-ae7f-11ea-9b76-9367784b87bf.png))

If it work I will integrate the change t master and build an new release this week
[jenkins-control-plugin-0.13.5-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4777020/jenkins-control-plugin-0.13.5-2020.1-bug217.zip)

**Comment by chen1234hao** [comment] 2020-06-15 02:09
hello MCMicS, i have try the plugin, and now it can not show the job structure, the error shows below:
2020-06-15 10:04:00,553 [  46031]  ERROR - intellij.openapi.progress.Task - loader constraint violation: loader com.intellij.util.lang.UrlClassLoader @7f9a81e8 wants to load interface org.apache.http.client.CredentialsProvider. A different interface with the same name was previously loaded by com.intellij.ide.plugins.cl.PluginClassLoader @24acfb3. (org.apache.http.client.CredentialsProvider is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @24acfb3, parent loader 'bootstrap') 
java.lang.LinkageError: loader constraint violation: loader com.intellij.util.lang.UrlClassLoader @7f9a81e8 wants to load interface org.apache.http.client.CredentialsProvider. A different interface with the same name was previously loaded by com.intellij.ide.plugins.cl.PluginClassLoader @24acfb3. (org.apache.http.client.CredentialsProvider is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @24acfb3, parent loader 'bootstrap')
	at com.intellij.util.net.IdeHttpClientHelpers$ApacheHttpClient4.setProxyCredentialsIfEnabled(IdeHttpClientHelpers.java:91)
	at com.intellij.util.net.IdeHttpClientHelpers$ApacheHttpClient4.setProxyCredentialsForUrlIfEnabled(IdeHttpClientHelpers.java:120)
	at org.codinjutsu.tools.jenkins.logic.RequestManager.authenticate(RequestManager.java:316)
	at org.codinjutsu.tools.jenkins.logic.LoginService$1.run(LoginService.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:434)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-15 10:04:00,554 [  46032]  ERROR - intellij.openapi.progress.Task - PyCharm 2020.1.1  Build #PC-201.7223.92 
2020-06-15 10:04:00,554 [  46032]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-06-15 10:04:00,554 [  46032]  ERROR - intellij.openapi.progress.Task - OS: Windows 10 
2020-06-15 10:04:00,554 [  46032]  ERROR - intellij.openapi.progress.Task - Plugin to blame: Jenkins Control Plugin version: 0.13.5-2020.1-bug217

**Comment by MCMicS** [comment] 2020-06-15 05:55
Thanks for feedback
I fix it soon. Sorry for the error. Only tested in debug mode and this loads fine.
Will provide a new version later the day

**Comment by MCMicS** [comment] 2020-06-15 06:39
[jenkins-control-plugin-0.13.5-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4778416/jenkins-control-plugin-0.13.5-2020.1-bug217.zip)

Could you try this please.

**Comment by chen1234hao** [comment] 2020-06-15 07:51
> [jenkins-control-plugin-0.13.5-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4778416/jenkins-control-plugin-0.13.5-2020.1-bug217.zip)
> 
> Could you try this please.

Great! it works , thanks for your contribute.

**Comment by diman82** [comment] 2020-06-15 08:00
> > [jenkins-control-plugin-0.13.5-2020.1-bug217.zip](https://github.com/MCMicS/jenkins-control-plugin/files/4778416/jenkins-control-plugin-0.13.5-2020.1-bug217.zip)
> > Could you try this please.
> 
> Great! it works , thanks for your contribute.

I can confirm that plugin works weel!

**Comment by MCMicS** [comment] 2020-06-15 08:39
Nice to hear
I will merge this the days and then release an official version.

Thanks for testing

**Comment by diman82** [comment] 2020-06-15 08:49
> Nice to hear
> I will merge this the days and then release an official version.
> 
> Thanks for testing

Thabks a lot for thr quick support!

**Comment by MCMicS** [comment] 2020-06-18 19:43
released with [0.13.5](../releases/tag/v0.13.5)

Feel free to create a new issue if something is wrong

**Closed** 2020-06-18 19:44 UTC
