### ISSUE TITLE
Cannot connect to in house server

### ISSUE THREAD

**Issue by NikolayMetchev** [MCMicS/jenkins-control-plugin#238] opened 2020-07-25 09:01 UTC
Hello,
I am trying to use the Jenkins plugin for our internal Jenkins server which uses Okta for authentication. I generated a token in the Jenkins server and used that as my password.
When I try and test the connection I get the attached error screen shot. It looks as though there server URL is null somewhere, however I have specified in the configuration as can be seen by the screenshot. Any help would be appreciated,. 

![image](https://user-images.githubusercontent.com/417373/88453301-9678c900-ce5d-11ea-8857-61377e905091.png)

**Comment by MCMicS** [comment] 2020-07-25 09:06
Seems duplicate of #234

Official release will be next week.
But you can try the eap

**Comment by NikolayMetchev** [comment] 2020-07-25 23:07
Running the latest EAP didn't get rid of the UI error. However the plugin was able to talk to the server.
However an exception occurred:

java.lang.Throwable: Assert: must be called on EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.util.ui.EDT.assertIsEdt(EDT.java:57)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getStripeTitle(ToolWindowImpl.kt:394)
	at com.intellij.openapi.wm.impl.StripeButton.updateText(StripeButton.java:332)
	at com.intellij.openapi.wm.impl.StripeButton.updatePresentation(StripeButton.java:322)
	at com.intellij.openapi.wm.impl.Stripe.updatePresentation(Stripe.java:442)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$notifyByBalloon$2.dispose(ToolWindowManagerImpl.kt:1288)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:111)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:189)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectNode.lambda$execute$0(ObjectNode.java:95)
	at com.intellij.openapi.util.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:189)
	at com.intellij.openapi.util.ObjectNode.execute(ObjectNode.java:71)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:137)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:121)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:111)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.notifyByBalloon(ToolWindowManagerImpl.kt:1253)
	at org.codinjutsu.tools.jenkins.view.BrowserPanel.notifyInfoJenkinsToolWindow(BrowserPanel.java:366)
	at org.codinjutsu.tools.jenkins.view.action.RunBuildAction.notifyOnGoingMessage(RunBuildAction.java:77)
	at org.codinjutsu.tools.jenkins.view.action.RunBuildAction$1.run(RunBuildAction.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by MCMicS** [comment] 2020-07-25 23:35
Will have a look at this

**Comment by MCMicS** [comment] 2020-07-27 17:54
@NikolayMetchev The EAP within IDEA is an old version. With new Version the error should gone because I use the IDEA Notification system now.
I work on last task and then an release will be created

Sorry for the issue

**Comment by MCMicS** [comment] 2020-07-28 19:49
released with [0.13.7](../releases/tag/v0.13.7)

**Closed by MCMicS** 2020-07-28 19:49 UTC
