### ISSUE TITLE
Support of Cloudbees Folder Plugin 

### ISSUE THREAD

**Issue by eugene-sy** [MCMicS/jenkins-control-plugin#83] opened 2014-08-01 07:52 UTC
It would be nice if plugin could work with Cloudbees Folder Plugin.

Now when you try to connect to Jenkins with this plugin, you get NPE. It seems, that json parser tries to get data from folder-job and fails.
Stacktrace:

```
null
java.lang.NullPointerException
at     org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.getJob(JenkinsJsonParser.java:175)
at     org.codinjutsu.tools.jenkins.logic.JenkinsJsonParser.createViewJobs(JenkinsJsonParser.java:296)
at org.codinjutsu.tools.jenkins.logic.RequestManager.loadJenkinsView(RequestManager.java:108)
at org.codinjutsu.tools.jenkins.view.BrowserPanel.loadJobs(BrowserPanel.java:412)
at org.codinjutsu.tools.jenkins.view.BrowserPanel.access$400(BrowserPanel.java:67)
at org.codinjutsu.tools.jenkins.view.BrowserPanel$LoadSelectedViewJob.run(BrowserPanel.java:511)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

My environment: 
IDEA 13.1.4
Jenkins 1.563
Java 1.6/1.7/1.8

**Comment by bbellanc** [comment] 2015-02-25 13:25
Can this issue be addressed?

**Comment by MCMicS** [comment] 2020-03-15 20:01
Duplicate of #128

**Closed by MCMicS** 2020-03-15 20:01 UTC
