### ISSUE TITLE
Jenkins plugin not working in WS 11

### ISSUE THREAD

**Issue by B-Enright** [MCMicS/jenkins-control-plugin#101] opened 2015-11-04 15:16 UTC
Please see the attached screenshots. I reported these to JetBrains, they said contact you. My OS is Win 8.1 Pro, with update.

Appreciate any fix you can provide.

benright@enrightindustrial.com

![webstorm_jenkins_pluginfailure11-3-15](https://cloud.githubusercontent.com/assets/2694343/10942195/cc960fec-82c3-11e5-9421-514ee931e7b8.JPG)
![webstorm_jenkins_pluginfailuredetails11-4-15](https://cloud.githubusercontent.com/assets/2694343/10942212/e11e21f2-82c3-11e5-8c3a-7f32be629c43.JPG)

**Comment by cezary-butler** [comment] 2015-11-04 18:32
Its a duplicate of #100.
For now you can use plugin from http://programisci.eu/en/jenkins-control-plugin-idea-15/
You should expect plugin with fix in jetbrains plugin repository soon.

**Comment by dboissier** [comment] 2015-11-04 21:17
Hi,

Build from @cezary-butler has just been uploaded to the Jetbrains plugins repository. You may be able to update it from your IDE

Sorry for the inconvenience (this often happens when new Jetbrains producs are released).

**Comment by dboissier** [comment] 2015-11-19 10:46
Hi @hhimanshu ,

@cezary-butler made robust fix for Idea 14 / 15 compatibility issue

 Could you please test this [SNAPSHOT](https://github.com/dboissier/jenkins-control-plugin/raw/master/snapshot/jenkins-control-plugin-0.9.4-SNAPSHOT-distribution.zip) and tell me if it works on your IDE?

Thanks.

**Comment by MCMicS** [comment] 2020-03-15 19:59
If error still occurs with 0.11.0 please feel free to reopen.

**Closed by MCMicS** 2020-03-15 19:59 UTC
